disabled_rules:
  - cyclomatic_complexity
  - file_length
  - type_body_length
  - line_length
  - force_cast
excluded:
- Pods
identifier_name:
  max_length: 50
  excluded:
    - x
    - i
    - y
    - db
    - id
